
#define FAMILY_NAME "link_agent_test"

// accept msg type
enum GNL_AGENT_ATTRIBUTE {
    GNL_AGENT_A_UNSPEC,
    GNL_AGENT_A_MSG,
    __GNL_AGENT_A_MAX,
};

enum GNL_AGENT_COMMAND {
    GNL_AGENT_C_UNSPEC,
    GNL_AGENT_C_ECHO_MSG,
    GNL_AGENT_C_REGISTER,
    __GNL_AGENT_C_MAX,
};

#define GNL_AGENT_ATTRIBUTE_ENUM_LEN  (__GNL_AGENT_A_MAX)
#define GNL_AGENT_ATTRIBUTE_COUNT (GNL_AGENT_ATTRIBUTE_ENUM_LEN -1)

#define GNL_AGENT_COMMAND_ENUM_LEN (__GNL_AGENT_C_MAX
#define GNL_AGENT_COMMAND_COUNT (GNL_AGENT_COMMAND_ENUM_LEN -1)


#define AGENT_GENL_NAME "linkagent"
#define AGENT_GENL_VERSION 1
#define AGENT_GENL_GROUP "linkagentgroup"
