
#define FAMILY_NAME "link_agent_test"

// accept msg type
// Register and Response
// command:
// GNL_AGENT_A_FIVE_TUPLE: NLA_NESTED
//      0: NLA_NESTED
//          GNL_AGENT_TUPLE_A_INADDR: NLA_U32   // only support ipv4 addr
//          GNL_AGENT_TUPLE_A_INPORT: NLA_U16
//          GNL_AGENT_TUPLE_A_OUTPORT: NLA_U16
//          GNL_AGENT_TUPLE_A_OUTADDR: NLA_U32
//          GNL_AGENT_TUPLE_A_PROTO: NLA_U8     // only support udp/tcp/icmp
// GNL_AGENT_A_PID: NLA_U16  
enum GNL_AGENT_ATTRIBUTE {
    GNL_AGENT_A_UNSPEC,
    GNL_AGENT_A_MSG,
    GNL_AGENT_A_FIVE_TUPLE,
    GNL_AGENT_A_PID,
    __GNL_AGENT_A_MAX,
};

enum GNL_AGENT_TUPLE_ATTRIBUTE {
    GNL_AGENT_TUPLE_A_UNSPEC,
    GNL_AGENT_TUPLE_A_INADDR,
    GNL_AGENT_TUPLE_A_INPORT,
    GNL_AGENT_TUPLE_A_OUTPORT,
    GNL_AGENT_TUPLE_A_OUTADDR,
    GNL_AGENT_TUPLE_A_PROTO,
    __GNL_AGENT_TUPLE_A_MAX,
};

enum GNL_AGENT_COMMAND {
    GNL_AGENT_C_UNSPEC,
    GNL_AGENT_C_ECHO_MSG,
    GNL_AGENT_C_REGISTER,
    GNL_AGENT_C_REGISTER_RESPONSE,
    __GNL_AGENT_C_MAX,
};

#define GNL_AGENT_ATTRIBUTE_ENUM_LEN  (__GNL_AGENT_A_MAX)
#define GNL_AGENT_ATTRIBUTE_COUNT (GNL_AGENT_ATTRIBUTE_ENUM_LEN -1)

#define GNL_AGENT_COMMAND_ENUM_LEN (__GNL_AGENT_C_MAX)
#define GNL_AGENT_COMMAND_COUNT (GNL_AGENT_COMMAND_ENUM_LEN -1)

#define GNL_AGENT_TUPLE_ATTRIBUTE_ENMU_LEN (__GNL_AGENT_TUPLE_A_MAX)
#define GNL_AGENT_TUPLE_ATTRIBUTE_COUNT (GNL_AGENT_TUPLE_ATTRIBUTE_ENMU_LEN -1)


#define AGENT_GENL_NAME "linkagent"
#define AGENT_GENL_VERSION 1
#define AGENT_GENL_GROUP "linkagentgroup"
